### ISSUE TITLE
Request to remove ?ver query string

### ISSUE THREAD

**Issue by blindpet** [Dridi/libvmod-querystring#17]
I am using this with Varnish 3 to prevent bots form using query strings and it's working great (no more weird hit ratio) so than you for that. I do not see it removing ?ver query strings like wp-emoji-release.min.js?ver=4.3.1 though

The code I am using is this

    if (req.url ~ "\.(ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|css|rss|atom|js|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf|cur)") {
    if (!req.url ~ "sccss") {
            set req.url = querystring.remove(req.url);
    }
    }

I tried adding set req.url = querystring.regfilter(req.url, "\?ver\=+."); after querystring.remove but no luck

**Comment by Dridi** [comment]
Could you please either show me a test case or the varnishlog output of such a transaction?

At first glance I would say that your first regex looks wrong, it contains spaces that probably prevent you from reaching line 3.

**Comment by blindpet** [comment]
Sorry that was a typo, I can see the querystring.remove working 

    30 VCL_call     c vmod_remove("/wp-content/themes/generatepress/style.css?devbproto-refresh=0.4084768013563007") "/wp-content/themes/generatepress/style.css"

However the regfilter is not removing for this and I'm struggling to catch a varnishlog since my filters aren't working

    http://www.htpcguides.com/wp-content/plugins/simple-share-buttons-plus/js/ssbp_page.js?ver=4.3.1

**Comment by Dridi** [comment]
Can you show me a `regfilter` example instead? Unlike `remove` that is quite straightforward, `regfilter` can be tricky.

**Comment by blindpet** [comment]
That's the thing, there seems to be nothing done to .js files

    31 RxURL        c /wp-content/themes/generatepress/js/superfish.min.js?ver=1.3.19
     31 RxProtocol   c HTTP/1.1
     31 RxHeader     c Host: www.htpcguides.com

**Comment by blindpet** [comment]
Finally found one

    VCL_call     c vmod_regfilter("/?sccss=1&ver=4.3.1", "(\?|\&)ver\=.+") "/?sccss=1&ver=4.3.1"

**Comment by Dridi** [comment]
Actually, the point of `regfilter` is to match the parameter itself, so that you don't need to take care of the separators. When I asked for an example I meant VCL code, sorry for the ambiguity. But from your two log records you could probably use `regfilter` this way:

```
querystring.regfilter(req.url, "v|ver")
```

It may be a bit too inclusive, so you way want to harden it this way:

```
querystring.regfilter(req.url, "^(v|ver)$")
```

It is more readable and should actually work with both examples. And as a matter of fact your second example didn't work, the query string is still there in the returned value.

When in doubt, you can instead rely on the more verbose `filter`:

```
querystring.filter(req.url, "v" + querystring.filtersep() + "ver");
```

But this one can grow out of control if you have too many parameters like all the one you can get if you have a google analytics campaign.

**Comment by Dridi** [comment]
This issue just timed out. Feel free to reopen it if you still have issues.
