### ISSUE TITLE
Bootstrap fail on CentOS 6.8

### ISSUE THREAD

**Issue by gsdevme** [Dridi/libvmod-querystring#27]
Hi,

Im running a CentOS box and the ./bootstrap seems to fail. 
```
configure.ac:31: warning: macro `AM_PROG_AR' not found in library
configure.ac:17: error: Autoconf version 2.68 or higher is required
configure.ac:17: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: autom4te failed with exit status: 63
```

I have `autoconf268` and `autoconf` but unsure how to make it use the 268.

**Comment by Dridi** [comment]
The `bootstrap` script is more of a maintainer thing, when you want to work directly on the git repository.

If you only need to build the module, grab the latest [1] release [2] and run the `configure` script instead. I would be surprised if it didn't work, I'm sure I made el6 builds in the past.

It seems I forgot to update the README to document it...

[1] https://github.com/Dridi/libvmod-querystring/releases/download/v1.0.1/vmod-querystring-1.0.1.tar.gz
[2] https://github.com/Dridi/libvmod-querystring/releases

**Comment by gsdevme** [comment]
Hi,

Sorry I just followed the docs, no worries. Just tried that but ran into the issue below.
```
checking for VARNISHAPI... no
configure: error: Package requirements (varnishapi) were not met:

No package 'varnishapi' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables VARNISHAPI_CFLAGS
and VARNISHAPI_LIBS to avoid the need to call pkg-config.
```

```
[gavin@gant-staging-web vmod-querystring-1.0.1]$ varnishd -V
varnishd (varnish-4.1.4 revision 4529ff7)
```

**Comment by Dridi** [comment]
On Dec 7, 2016 19:47, "Gavin Staniforth" <notifications@github.com> wrote:
>
> Hi,
>
> Sorry I just followed the docs, no worries. Just tried that but ran into
the issue below.

Don't be sorry, out will help me improve the docs ;)

> checking for VARNISHAPI... no configure: error: Package requirements
(varnishapi) were not met: No package 'varnishapi' found Consider adjusting
the PKG_CONFIG_PATH environment variable if you installed software in a
non-standard prefix. Alternatively, you may set the environment variables
VARNISHAPI_CFLAGS and VARNISHAPI_LIBS to avoid the need to call pkg-config.

You need to install the varnish-libs-devel package.

**Comment by gsdevme** [comment]
Seems I need to get a copy of `rst2man` on the server, not included in IUS or EPEL from the looks of it.

**Comment by gsdevme** [comment]
Argh that can be installed with `sudo yum install python-docutils` looks like I have it built now :)

**Comment by gsdevme** [comment]
Thanks for the help! and the plugin. I've built RPMs now to help distribution, closing as its not an issue. for reference https://github.com/usemarkup/libvmod-querystring-rpm

**Comment by Dridi** [comment]
FYI, I will close this ticket after I fixed the README ;)

**Comment by Dridi** [comment]
I had a look at the README and it actually contains almost all the information you needed. I will turn the README upside down to better segregate `configure` vs `bootstrap` usage. Also thanks for uploading RPMs. This module has actually been accepted in Fedora and I may push it to EPEL 7 too (because EPEL 6 ships an older Varnish) but circumstances have delayed this effort for now.

Also I had no idea that folks at @fastly were using this module, thanks a lot for letting me know! However their version doesn't match the one you uploaded, so their documentation won't help. Please link to the release docs [1] instead, I upload the manual as a PDF [2] since the 1.0 release.

Now it's between me and the README!

[1] https://github.com/Dridi/libvmod-querystring/releases/tag/v1.0.1
[2] https://github.com/Dridi/libvmod-querystring/releases/download/v1.0.1/vmod_querystring.pdf

**Comment by Dridi** [comment]
I just pushed a bunch of commits, please have a look at the README in the current master branch and let me know what you think.

**Comment by Dridi** [comment]
ETIMEDOUT
