### ISSUE TITLE
Release for Varnish 6?

### ISSUE THREAD

**Issue by SpikesDivZero** [Dridi/libvmod-querystring#38]
Hi Dridi,

I'm not sure if this is the best place to make this request, and if not, my apologies for the troubles.

I was looking at packaging this for Varnish 6, and it looks like the latest released version (1.0.4) doesn't contain the fixes you'd applied to have the VMOD work with Varnish 6. Would you be willing to cut a minor release that has the match_proto fix in there?

I tested the VMOD using `make distcheck` on a Varnish 6 host, then running `./configure && make check` in VMs containing Varnish 5.2 and 6.0 and it looked to work without issue.

Thanks so much for your work on this, it's been quite helpful!
-Spikes

**Comment by Dridi** [comment]
There's one documentation bit I'd like to polish before cutting a new release.

Also it may take some time since I'll need to double-check that the VMOD indeed builds against advertised versions, RPM and Deb packaging still works, and right now I have little time for that. Usually I take care of this faster when we release a breaking Varnish major but these days are packed :(

I'm glad this vmod is helping you. Don't hesitate to star the repository and most importantly open issues if anything could be added or improved in your opinion.

**Comment by SpikesDivZero** [comment]
Sure thing! If I may, what OS/Release matrixes are you targeting?

**Comment by Dridi** [comment]
I'm targeting all releases since Varnish 4.1.3 according to the README, and it should work from a release archive built against at least Varnish 5.1.1, and I want to ensure that Debs/RPMs build fine against the Varnish 6 official packages because they changed substantially :)

I need a couple distraction-free hours to check all that. Can you roll with a build from the master branch for now? Otherwise I can upload a temporary release archive from current master.

**Comment by SpikesDivZero** [comment]
Oh, no worries. I wasn't trying to rush. I figured I'd ask as, while I don't expect to have any such deliverable/PR, I've been trying to find good ways to automate build testing for another one of my projects, and having more context as to other practical uses is always beneficial in striving to figure out how best to implement such a project :)

**Comment by Dridi** [comment]
Sorry about that, I have little to no free time to allocate to software maintenance these days and this vmod isn't part of my day job. You should be able to build an RPM with the following steps until a proper release is out:

* check out master
* install build-from-git dependencies
* `./bootstrap && make dist`

And then you have a release-like tarball you can build an RPM from.

**Comment by Dridi** [comment]
1.0.5 is out, enjoy :)
