### ISSUE TITLE
Add bootstrap script to release tarball

### ISSUE THREAD

**Issue by glensc** [Dridi/libvmod-querystring#48]
... so when downloading release tarball the ./bootstrap command works as well.

Typically not needed, but useful when patching and you don't want to modify (much) build scripts.

**Comment by glensc** [comment]
The thing is that nobody's perfect, a release may be broken, may be needed to take the release and patch it.

The other thing is that there's always a way for a workaround, just the workaround length may be different.

as for the cloning vs download, the situation was at the time, that there were many fixes on master branch that wasn't released, so I preferred cloning instead.

**Comment by Dridi** [comment]
I'm really reluctant to the idea of adding a development-only artifact to a release archive, but since many seem to prefer cloning the repository over using a vetted release archive I decided to make the script a tiny bit more friendly.

I'm not sure about the patching use case here, I have done that somewhat recently on the 2.0.2 release archive:

https://src.fedoraproject.org/rpms/vmod-querystring/c/a1ae9ee0754248476b3353df24fb4d1d6a0a3edc

It took me a hot minute to generate the patch from the commit, and update the RPM spec to apply it, without involving a bootstrap. It was faster for me considering how little time I could spend in August on what ended up being 2.0.3 earlier this week.

I think e48092e...387a02f should be enough for now, and I will leave the bootstrap out.

**Comment by Dridi** [comment]
When I closed this ticket I didn't see your reply (and I got the email notification 1h later) so I will take the time to reply.

I agree that a release may not be perfect, especially in the event of a dot-zero Varnish release, especially for a vmod that follows a versioning scheme based on its own features and not tied to a specific Varnish series. My spare time has been so scarce between 6.5 and now that I had to postpone the release work much longer than I would have liked.

The release model consists in providing an archive that does not rely on most of the build system, and bootstrapping that is a development task. I know that the bootstrap script is a convenience, it's actually very convenient for me, it enables some configure options geared toward development for me that aren't very suitable for production.

For example, in https://github.com/Dridi/libvmod-querystring/issues/47#issuecomment-962467330 I had to disable warnings because Varnish 7 apparently triggers one of them in one of its headers, something outside of this vmod's scope that only I should run into since I work with warnings turned on and treated as errors.

Like I showed in the previous comment, patching shouldn't be a problem, it wasn't a problem for me on Fedora's build system where the release archive is used. But granted, I needed to run `git-format-patch` to get there, it's a bit more involved than cloning the tip of the master branch.

On the other hand I can get rid of the following direct dependencies when I work from a release archive:

- autoconf
- automake
- libtool
- rst2man

At this point all you have to do is running `./configure` instead of `./bootstrap`.

So the tradeoffs are:

- applying a patch on top of a release archive vs cloning the right head
- dragging more dependencies vs calling the configure script directly
- exporting the aclocal path vs not having to care (this one will go away with 2.0.4)

Exporting the pkg-config path is mandatory either way if Varnish was installed outside of the default location, there's no way around that.

I understand that the bootstrap script looks convenient but it's really geared towards development, and if the main pain point is the lack of reactivity when a new Varnish release is out, I can only promise to do my best next time around. Ironically, fffe7583af018e9a9424139d9fc4080586cf3f90 was ready before the Varnish 6.6.0 release but by March 15th it was too complicated for me to get a chance to sit down and add the support for the VCL native REGEX type.

**Comment by glensc** [comment]
something funny happening here in github. [my reply](https://github.com/Dridi/libvmod-querystring/issues/48#issuecomment-962576006) is 3 minutes earlier than [the post I replied to](https://github.com/Dridi/libvmod-querystring/issues/48#issuecomment-962569652)
