### ISSUE TITLE
Does not build on Varnish 4.0.0-tp2

### ISSUE THREAD

**Issue by gauthier-delacroix** [Dridi/libvmod-querystring#6]
Hi, 

I've seen that your VMOD is prepared for Varnish 4.0.0 tp1 but, tp2 VMOD structure has changed a lot and I don't think you'll be able to keep the VMOD compatible with both v3 and v4 in the same source...

I can help converting the VMOD structure for tp2 but v3 and v4-tp1 compatibility would be lost...

**Comment by Dridi** [comment]
With Varnish 4.1 being close to a release and the end of life of Varnish 3, in the next release I will change APIs to take advantages of Varnish 4+ features and get rid of the general complexity that V3+V4 support incurs.

This vmod has worked with Varnish 4 since the very first preview, with no changes in the code base. This issue can be closed now :)
